# Generated by Django 5.0.3 on 2024-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_tache_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="description",
            field=models.TextField(default=models.CharField(max_length=250)),
        ),
    ]
